name: app_device_info
description: "A Flutter package that provides comprehensive device and application information."
version: 0.0.1
homepage: https://github.com/Saad-Rajpoot/AppDeviceInfo
license: BSD-3-Clause

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.0 # Adjust the version as necessary
  package_info_plus: ^8.0.0 # Adjust the version as necessary

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
